version: '3'
services:
  gptbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - redis
    env_file:
      - .env_dev

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data: