version: '3'
services:
  gptbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env_dev
    networks:
      - gptbot_network

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - gptbot_network

volumes:
  redis_data:

networks:
  gptbot_network: